
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./public/gltf/gorilla/scene.gltf --transform
Author: Filip (https://sketchfab.com/filip.hans.nyberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-gorilla-ad28003205884841a028e80edb4089ef
Title: Free Gorilla
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('/scene-transformed.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Cylinder002_Gorilla_0.geometry} material={gltf.materials.Gorilla} rotation={[-Math.PI / 2, 0, 0,]} scale={100} />
<T.Mesh geometry={gltf.nodes.Sphere001_Material001_0.geometry} material={gltf.materials['Material.001']} position={[0, 4.38, 7.35,]} rotation={[-Math.PI / 2, 0, 0,]} scale={100} />

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	