<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./scene.gltf --transform
Author: Carlos.Maciel (https://sketchfab.com/Carlos.Maciel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sword-fish-9f076eb541a44a96b65e53a4062db506
Title: Sword Fish
-->

<script>
	import { T } from "@threlte/core";
	import { useDraco, useGltf } from "@threlte/extras";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = useDraco();
	const gltf = useGltf("/glb/swordfish.glb", {
		dracoLoader,
	});
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Object_2.geometry}
			material={gltf.materials["Material.001"]}
			rotation={[-Math.PI / 2, 0, 0]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
