<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./gltf/scene.gltf --transform
Author: Trident.AI (https://sketchfab.com/Trident.AI)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/tiger-2472faceb5f74008a2ac1322202ec585
Title: Tiger
-->

<script>
	/**
	 * 1. glTF Converted format herunterladen
	 * 2. npx @threlte/gltf@latest ./path/to/file --transform
	 * 3. Dann bekommst du einmal ein scene-transformed.glb und eine scene.svelte
	 * 	a. Die scene.svelte ist in Home.svelte eingebunden (das nicht weiter verwenden)
	 * 4. tier zu index.js hinzufügen
	 *
	 */

	import { T } from "@threlte/core";
	import { useDraco, useGltf } from "@threlte/extras";

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = useDraco();
	const gltf = useGltf("/glb/tiger.glb", {
		dracoLoader,
	});
</script>

{@render children?.()}

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group scale={0.01}>
			<T.Mesh
				geometry={gltf.nodes.Mesh1_Mesh1007_Material001_0.geometry}
				material={gltf.materials["Material.001"]}
				scale={100}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
